classOrder = [
	"Bootstrapper",
]

title = "Bootstrapper"
gitRepoUrl = "https://github.com/LDgerrits/Bootstrapper"

gitSourceBranch = "main"
changelog = false

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Predictable Order"
description = "Set a specific execution flow for your modules."

[[home.features]]
title = "Event Binding"
description = "Connect modules directly to RunService events or custom signals."

[[home.features]]
title = "Memory Profiling"
description = "Automatically assigns `debug.setmemorycategory` to every module's thread and RunService loop."

organizationName = "LDGerrits"
projectName = "Bootstrapper"
url = "https://LDGerrits.github.io"
baseUrl = "/Bootstrapper/"
