[package]
name = "ldgerrits/bootstrapper"
description = "A centralized Roblox scheduler and module loader. Take 100% explicit control over your execution flow to eliminate unpredictable load orders, race conditions, and event connections."
version = "1.0.16"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/*", "wally.toml", "default.project.json", "LICENSE.md"]
