[package]
name = "ldgerrits/bootstrapper"
description = "A lightweight, agnostic scheduler for Roblox. Enforce a deterministic order of operations for modules across startup and (RunService) events."
version = "1.0.15"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/*", "wally.toml", "default.project.json", "LICENSE.md"]
